"""Default values for mcp-video.

All default constants used across the codebase are centralized here
per AGENTS.md Rule 12.
"""

from __future__ import annotations

# Re-export encoding defaults from limits for backward compatibility
from .limits import DEFAULT_CRF, DEFAULT_FFMPEG_TIMEOUT, DEFAULT_PRESET  # noqa: F401

# Quality presets
DEFAULT_QUALITY = "high"
DEFAULT_FORMAT = "mp4"

# Video dimensions
DEFAULT_FPS = 30
DEFAULT_COMPOSITION_WIDTH = 1920
DEFAULT_COMPOSITION_HEIGHT = 1080
DEFAULT_COMPOSITION_FPS = DEFAULT_FPS
DEFAULT_GIF_FPS = 15
DEFAULT_THUMBNAIL_WIDTH = 320
DEFAULT_STORYBOARD_WIDTH = 480
DEFAULT_STORYBOARD_HEIGHT = 270

# Audio defaults
DEFAULT_SAMPLE_RATE = 44100
DEFAULT_CHANNELS = 1
DEFAULT_AUDIO_CHANNELS = 2
DEFAULT_AUDIO_VOLUME = 0.5
DEFAULT_LUFS_TARGET = -16.0
DEFAULT_LRA_TARGET = 11.0
DEFAULT_AUDIO_BITRATE = "128k"
DEFAULT_PROCEDURAL_AUDIO_BED_WARNING_SECONDS = 10.0

# Text overlay defaults
DEFAULT_FONT_SIZE = 48
DEFAULT_TEXT_COLOR = "white"
DEFAULT_TEXT_POSITION = "top-center"
DEFAULT_SAFE_SUBTITLE_FONT_SIZE = 24
DEFAULT_SUBTITLE_MAX_CHARS_PER_LINE = 42
DEFAULT_SUBTITLE_MAX_LINES = 3

# Agent/release guardrail defaults
MIN_FFMPEG_VERSION_HARD = 5
MIN_FFMPEG_VERSION = 6
DEFAULT_GLOW_MAX_SAFE_INTENSITY = 0.25
DEFAULT_QUALITY_GATE_SCORE = 80.0

# Transition defaults
DEFAULT_TRANSITION_DURATION = 1.0

# Grid/layout defaults
DEFAULT_GRID_CELL_WIDTH = 640
DEFAULT_GRID_CELL_HEIGHT = 480
