"""After Effects ExtendScript (JSX) export engine.

Generates a .jsx file that, when run inside After Effects via
File > Scripts > Run Script File, reconstructs the edit as a
new composition with all clips trimmed and placed at the correct
timecodes — no intermediary NLE required.

Added by cocothinks-labs: https://github.com/cocothinks-labs/mcp-video
"""

from __future__ import annotations

import os
from dataclasses import dataclass

from .engine_edl import EDLClip
from .engine_probe import probe
from .errors import MCPVideoError
from .models import Timeline


@dataclass
class AEScriptResult:
    output_path: str
    event_count: int
    comp_name: str
    fps: float
    width: int
    height: int


# ---------------------------------------------------------------------------
# JSX template helpers
# ---------------------------------------------------------------------------

_JSX_HEADER = """\
// mcp-video After Effects import script
// Generated by cocothinks-labs/mcp-video
// Run via: File > Scripts > Run Script File
// -------------------------------------------------------
// Comp: {comp_name}  |  {width}x{height}  |  {fps} fps
// -------------------------------------------------------

(function () {{
    app.beginUndoGroup("mcp-video import");
    try {{
        var fps        = {fps};
        var compName   = {comp_name_js};
        var compWidth  = {width};
        var compHeight = {height};
        var compDuration = {comp_duration};
        var pixelAspect = 1.0;

        var comp = app.project.items.addComp(
            compName, compWidth, compHeight, pixelAspect, compDuration, fps
        );

        // Imported footage items, keyed by absolute path
        var footage = {{}};

        function importOrReuse(filePath) {{
            if (footage[filePath]) return footage[filePath];
            var f = new File(filePath);
            if (!f.exists) {{
                alert("File not found:\\n" + filePath);
                return null;
            }}
            var io = new ImportOptions(f);
            io.sequence = false;
            var item = app.project.importFile(io);
            footage[filePath] = item;
            return item;
        }}

"""

_JSX_CLIP = """\
        // Event {idx}: {clip_name}
        (function () {{
            var avItem = importOrReuse({src_path_js});
            if (!avItem) return;
            var layer = comp.layers.add(avItem);
            // Align source so that srcIn lands on recordIn in the comp
            layer.startTime = {start_time};
            layer.inPoint   = {rec_in};
            layer.outPoint  = {rec_out};
        }})();

"""

_JSX_FOOTER = """\
        app.project.activeItem;  // return comp to caller
        comp.openInViewer();
        alert("mcp-video import complete!\\n" +
              "{event_count} clip(s) placed in comp \\"" + compName + "\\".");
    }} catch (e) {{
        alert("mcp-video script error:\\n" + e.toString());
    }} finally {{
        app.endUndoGroup();
    }}
}})();
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def export_aescript_from_clips(
    clips: list[EDLClip],
    output_path: str,
    comp_name: str = "mcp-video export",
    fps: float = 25.0,
    width: int = 1920,
    height: int = 1080,
) -> AEScriptResult:
    """Generate an After Effects JSX script from a list of EDLClip decisions.

    When the script is run in AE it creates a new composition with every clip
    trimmed and placed at the correct record timecode — equivalent to what an
    EDL would produce in Premiere Pro, but natively in After Effects.
    """
    if not clips:
        raise MCPVideoError(
            "No clips provided for AE script export",
            error_type="validation_error",
            code="empty_clip_list",
        )

    # Calculate total comp duration
    total_duration = sum(c.src_out - c.src_in for c in clips)
    if total_duration <= 0:
        raise MCPVideoError(
            "Total edit duration is zero or negative",
            error_type="validation_error",
            code="invalid_duration",
        )

    def js_string(s: str) -> str:
        """Wrap a Python string as a JS string literal with escaped backslashes."""
        escaped = s.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'

    lines: list[str] = [
        _JSX_HEADER.format(
            comp_name=comp_name,
            comp_name_js=js_string(comp_name),
            fps=fps,
            width=width,
            height=height,
            comp_duration=round(total_duration, 6),
        )
    ]

    rec_pos = 0.0
    for idx, clip in enumerate(clips, start=1):
        duration = clip.src_out - clip.src_in
        rec_in   = rec_pos
        rec_out  = rec_pos + duration
        # AE startTime offset: shifts the layer so srcIn aligns with rec_in
        # At comp time rec_in, AE reads: rec_in - start_time = src_in ✓
        start_time = rec_in - clip.src_in

        lines.append(
            _JSX_CLIP.format(
                idx=idx,
                clip_name=os.path.basename(clip.source_path),
                src_path_js=js_string(clip.source_path.replace("\\", "/")),
                start_time=round(start_time, 6),
                rec_in=round(rec_in, 6),
                rec_out=round(rec_out, 6),
            )
        )
        rec_pos += duration

    lines.append(_JSX_FOOTER.format(event_count=len(clips)))

    jsx_content = "".join(lines)
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(jsx_content)

    return AEScriptResult(
        output_path=output_path,
        event_count=len(clips),
        comp_name=comp_name,
        fps=fps,
        width=width,
        height=height,
    )


def export_aescript_from_timeline(
    timeline: Timeline | dict,
    output_path: str,
    comp_name: str = "mcp-video export",
    fps: float | None = None,
    width: int | None = None,
    height: int | None = None,
) -> AEScriptResult:
    """Convert a mcp-video Timeline JSON to an After Effects JSX script."""
    if isinstance(timeline, dict):
        timeline = Timeline.model_validate(timeline)

    clips: list[EDLClip] = []
    detected_fps: float | None = None
    detected_w: int | None = None
    detected_h: int | None = None

    for track in timeline.tracks:
        if track.type != "video":
            continue
        for clip in track.clips:
            src_in = clip.trim_start or 0.0
            if clip.trim_end is not None:
                src_out = clip.trim_end
            elif clip.duration is not None:
                src_out = src_in + clip.duration
            else:
                try:
                    info = probe(clip.source)
                    src_out = float(info.duration)
                    if detected_fps is None and info.fps:
                        detected_fps = float(info.fps)
                    if detected_w is None and info.width:
                        detected_w = info.width
                    if detected_h is None and info.height:
                        detected_h = info.height
                except Exception as exc:
                    raise MCPVideoError(
                        f"Cannot determine duration for clip '{clip.source}'. "
                        "Provide trim_end or duration in the timeline.",
                        error_type="validation_error",
                        code="missing_clip_duration",
                    ) from exc
            clips.append(EDLClip(source_path=clip.source, src_in=src_in, src_out=src_out))

    if not clips:
        raise MCPVideoError(
            "Timeline contains no video clips to export as AE script",
            error_type="validation_error",
            code="empty_timeline",
        )

    resolved_fps = fps or detected_fps or 25.0
    resolved_width = width or (timeline.width if timeline.width else detected_w) or 1920
    resolved_height = height or (timeline.height if timeline.height else detected_h) or 1080

    return export_aescript_from_clips(
        clips,
        output_path,
        comp_name=comp_name,
        fps=resolved_fps,
        width=resolved_width,
        height=resolved_height,
    )
